spring:
    datasource:
      url: jdbc:sqlserver://DEVSTRO-WIN11:1433;encrypt=true;trustServerCertificate=true;databaseName=Flights
      username: sa
      password: Onlyforme1334!
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        show-sql: true
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
server:
  port: 8080